<a href="https://colab.research.google.com/github/ahzahid81/IntroductionToDataScienceInPython/blob/main/Module2_TheSeriesDataStructure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
students = ['Alice', 'Jack', 'Molly']
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [ ]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [ ]:
students = ['Alice', 'Jack', None]
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [ ]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
import numpy as np
np.nan == None

False

In [ ]:
np.nan == np.nan

False

In [ ]:
np.isnan(np.nan)

True

In [ ]:
students_scores = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English'}
s = pd.Series(students_scores)
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
s.index

Index(['Alice', 'Jack', 'Molly'], dtype='object')

In [ ]:
students = [("Alice","Brown"), ("Jack", "White"), ("Molly", "Green")]
pd.Series(students)

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object

In [ ]:
import pandas as pd
s = pd.Series(['Physics', 'Chemistry', 'English'], index=['Alice', 'Jack', 'Molly'])
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
students_scores = {
    'Alice': 'Physics',
    'Jack': 'Chemistry',
    'Molly': 'English'
}
s = pd.Series(students_scores, index=['Alice', 'Molly', 'Sam'])
s

Alice    Physics
Molly    English
Sam          NaN
dtype: object

In [ ]:
students_classes = {
    'Alice': 'Physics',
    'Jack': 'Chemistry',
    'Molly': 'English',
    'Sam': 'History'
}
s = pd.Series(students_classes)
s

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [ ]:
s.iloc[3]

'History'

In [ ]:
s.loc['Molly']

'English'

In [ ]:
s[3]

<ipython-input-20-354d6d7fa2e4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[3]

'History'

In [ ]:
s['Molly']

'English'

In [ ]:
class_code = {99: 'Physics',
              100: 'Chemistry',
              101: 'English',
              102: 'History'}
s = pd.Series(class_code)
s

99       Physics
100    Chemistry
101      English
102      History
dtype: object

In [ ]:
s[0]

KeyError: 0

In [ ]:
grades = pd.Series([90, 80, 70, 60])
total = 0
for grade in grades:
    total += grade
print(total/len(grades))

75.0

In [ ]:
import numpy as np

total = np.sum(grades)
print(total/len(grades))

75.0

In [ ]:
import pandas as pd
numbers = pd.Series(np.random.randint(0,1000,10000))
numbers.head()

0    994
1    382
2    890
3    984
4    756
dtype: int64

In [ ]:
len(numbers)

10000

In [ ]:
%%timeit -n 100
total = 0
for number in numbers:
    total += number
total/len(numbers)

2.12 ms ± 793 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [ ]:
%%timeit -n 100
total = np.sum(numbers)
total/len(numbers)

33.3 µs ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [ ]:
numbers.head()

0    994
1    382
2    890
3    984
4    756
dtype: int64

In [ ]:
numbers +=2

In [ ]:
numbers.head()

0    1002
1     390
2     898
3     992
4     764
dtype: int64

In [ ]:
%%timeit -n 10

import pandas as pd
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.items():
    s.loc[label]= value+2

422 ms ± 28.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
%%timeit -n 10

import pandas as pd
s = pd.Series(np.random.randint(0,1000,10000))
s+=2
#

277 µs ± 75.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
s = pd.Series([1, 2, 3])
s.loc['History'] = 102
s

0            1
1            2
2            3
History    102
dtype: int64

In [ ]:
students_classes = pd.Series({'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English',
                   'Sam': 'History'})
students_classes

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [ ]:
kelly_classes = pd.Series(['Philosophy', 'Arts', 'Math'], index=['Kelly', 'Kelly', 'Kelly'])
kelly_classes

Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
all_students_classes = pd.concat([students_classes, kelly_classes])
all_students_classes

Alice       Physics
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
students_classes

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [ ]:
all_students_classes

Alice       Physics
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
all_students_classes.loc['Kelly']

Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object

In [ ]:
import pandas as pd
record1 = pd.Series({'Name': 'Alice',
                   'Class': 'Physics',
                   'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                   'Class': 'Chemistry',
                   'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                   'Class': 'Biology',
                   'Score': 90})

In [ ]:
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school1'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [ ]:
students = [{'Name': 'Alice',
             'Class': 'Physics',
             'Score' : 85},
            {'Name' : 'Jack',
             'Class' : 'Chemistry',
             'Score' : 82},
            {'Name' : 'Helen',
             'Class' : 'Biology',
             'Score' : 98}]

df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     98

In [ ]:
df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [ ]:
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     98

In [ ]:
type (df.loc['school2'])

pandas.core.series.Series

In [ ]:
type (df.loc['school1'])

pandas.core.frame.DataFrame

In [ ]:
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     98

In [ ]:
df.loc['school1', 'Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     98

In [ ]:
df.T

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       98

In [ ]:
df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
df['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df.loc['school1']['Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [ ]:
print(type(df.loc['school1']))
print(type(df.loc['school1']['Name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [ ]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     98

In [ ]:
df.loc[:,['Name', 'Score']]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     98

In [ ]:
df.drop('school1')

         Name      Class  Score
school2  Jack  Chemistry     82

In [ ]:
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     98

In [ ]:
copy_df = df.copy()
copy_df.drop('Name', inplace=True, axis=1)
copy_df

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     98

In [ ]:
del copy_df['Class']
copy_df

         Score
school1     85
school2     82
school1     98

In [ ]:
copy_df

         Score
school1     85
school2     82
school1     98

In [ ]:
df['ClassRanking']=None
df

          Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     98         None

In [6]:
!cat Admission_Predict.csv

cat: Admission_Predict.csv: No such file or directory

In [10]:
# prompt: In this drive file, I have a csv file . File Name is: datasets/Admission_Predict.csv. But !cat datasets/Admission_Predict.csv not working

import pandas as pd
# Assuming the file is in your Google Drive's 'datasets' folder.
# Mount your Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Specify the full path to your CSV file in Google Drive
file_path = '/content/drive/MyDrive/datasets/Admission_Predict.csv'

try:
    # Read the CSV file using pandas
    df = pd.read_csv(file_path)
    df = pd.read_csv('/content/drive/MyDrive/datasets/Admission_Predict.csv')

    # Now you can work with the DataFrame 'df'
    print(df.head())  # Display the first few rows
    # ... perform other operations with the dataframe

except FileNotFoundError:
    print(f"Error: File not found at {file_path}. Please check the file path.")
except pd.errors.EmptyDataError:
    print(f"Error: The file at {file_path} is empty.")
except pd.errors.ParserError:
    print(f"Error: Could not parse the file at {file_path}. Check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65
1           2        324          107                  4  4.0   4.5  8.87
2           3        316          104                  3  3.0   3.5  8.00
3           4        322          110                  3  3.5   2.5  8.67
4           5        314          103                  2  2.0   3.0  8.21

   Research  Chance of Admit
0         1              0.92
1         1              0.76
2         1              0.72
3         1              0.80
4         0              0.65

In [12]:
import pandas as pd
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [13]:
new_df = df.rename(columns={'GRE Score': 'GRE Score', 'TOEFL Score': 'TOEFL Score',
                   'University Rating': 'University Rating', 'SOP': 'Statement of Purpose',
                   'LOR ': 'Letter of Recommendation', 'CGPA': 'CGPA',
                   'Research': 'Research', 'Chance of Admit ': 'Chance of Admit'})
new_df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [14]:
new_df = new_df.rename(columns={'LOR ': 'Letter of Recommendation'})
new_df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [15]:
new_df = new_df.rename(mapper=str.strip, axis='columns')
new_df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [16]:
Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOR', 'LOR', 'CGPA', 'Research', 'Chance of Admit'], dtype = 'object')

NameError: name 'Index' is not defined

In [17]:
cols = list(df.columns)
cols = [x.lower().strip() for x in cols]
df.columns = cols
df.head()

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [20]:
import pandas as pd
df = pd.read_csv(file_path, index_col=0)
df.columns = [x.lower().strip() for x in df.columns]
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [21]:
admit_mask = df['chance of admit'] > 0.7
admit_mask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398     True
399    False
400     True
Name: chance of admit, Length: 400, dtype: bool

In [22]:
df.where(admit_mask).head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.where(admit_mask).dropna().head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [24]:
df[df['chance of admit'] > 0.7].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90

In [25]:
df['gre score'].head()

Serial No.
1    337
2    324
3    316
4    322
5    314
Name: gre score, dtype: int64

In [26]:
df[df['gre score']>320].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90
7,321,109,3,3.0,4.0,8.20,1,0.75

In [27]:
(df['chance of admit']>0.7)&(df['chance of admit']<0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [28]:
df['chance of admit'].gt(0.7)&df['chance of admit'].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [29]:
df['chance of admit'].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...
396    False
397    False
398    False
399     True
400    False
Name: chance of admit, Length: 400, dtype: bool

In [30]:
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [31]:
df['Serial Number'] = df.index
df = df.set_index('chance of admit')
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,Serial Number
chance of admit,,,,,,,,
0.92,337,118,4,4.5,4.5,9.65,1,1
0.76,324,107,4,4.0,4.5,8.87,1,2
0.72,316,104,3,3.0,3.5,8.00,1,3
0.80,322,110,3,3.5,2.5,8.67,1,4
0.65,314,103,2,2.0,3.0,8.21,0,5

In [32]:
df = df.reset_index()
df.head()

,chance of admit,gre score,toefl score,university rating,sop,lor,cgpa,research,Serial Number
0,0.92,337,118,4,4.5,4.5,9.65,1,1
1,0.76,324,107,4,4.0,4.5,8.87,1,2
2,0.72,316,104,3,3.0,3.5,8.00,1,3
3,0.80,322,110,3,3.5,2.5,8.67,1,4
4,0.65,314,103,2,2.0,3.0,8.21,0,5

In [34]:
df = pd.read_csv('/content/drive/MyDrive/datasets/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [35]:
df['SUMLEV'].unique()

array([40, 50])

In [36]:
df = df[df['SUMLEV'] == 50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [38]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2013', 'BIRTHS2014', 'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014', 'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

,STNAME,CTYNAME,BIRTHS2010,BIRTHS2011,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,636,574,623,600,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,2187,2160,2186,2240,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,335,283,260,269,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,266,259,247,253,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,744,646,618,603,57373,57711,57776,57734,57658,57673

In [39]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

                        BIRTHS2010  BIRTHS2011  BIRTHS2013  BIRTHS2014  \
STNAME  CTYNAME
Alabama Autauga County         151         636         574         623
        Baldwin County         517        2187        2160        2186
        Barbour County          70         335         283         260
        Bibb County             44         266         259         247
        Blount County          183         744         646         618

                        BIRTHS2015  POPESTIMATE2010  POPESTIMATE2011  \
STNAME  CTYNAME
Alabama Autauga County         600            54660            55253
        Baldwin County        2240           183193           186659
        Barbour County         269            27341            27226
        Bibb County            253            22861            22733
        Blount County          603            57373            57711

                        POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
STNAME  CTYNAME
Alabama Autauga County            55175            55038            55290
        Baldwin County           190396           195126           199713
        Barbour County            27159            26973            26815
        Bibb County               22642            22512            22549
        Blount County             57776            57734            57658

                        POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County            55347
        Baldwin County           203709
        Barbour County            26489
        Bibb County               22583
        Blount County             57673

In [40]:
df.loc['Michigan', 'Washtenaw County']

BIRTHS2010            977
BIRTHS2011           3826
BIRTHS2013           3662
BIRTHS2014           3683
BIRTHS2015           3709
POPESTIMATE2010    345563
POPESTIMATE2011    349048
POPESTIMATE2012    351213
POPESTIMATE2013    354289
POPESTIMATE2014    357029
POPESTIMATE2015    358880
Name: (Michigan, Washtenaw County), dtype: int64

In [41]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

                           BIRTHS2010  BIRTHS2011  BIRTHS2013  BIRTHS2014  \
STNAME   CTYNAME
Michigan Washtenaw County         977        3826        3662        3683
         Wayne County            5918       23819       23377       23607

                           BIRTHS2015  POPESTIMATE2010  POPESTIMATE2011  \
STNAME   CTYNAME
Michigan Washtenaw County        3709           345563           349048
         Wayne County           23586          1815199          1801273

                           POPESTIMATE2012  POPESTIMATE2013  POPESTIMATE2014  \
STNAME   CTYNAME
Michigan Washtenaw County           351213           354289           357029
         Wayne County              1792514          1775713          1766008

                           POPESTIMATE2015
STNAME   CTYNAME
Michigan Washtenaw County           358880
         Wayne County              1759335

In [43]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/datasets/class_grades.csv')
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17      NaN     63.15  48.89
3       7         NaN       NaN    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00       NaN  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

In [44]:
df.dropna().head(10)

    Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0        5       57.14     34.09    64.38     51.48  52.50
1        8       95.05    105.49    67.50     99.07  68.33
4        8       91.32     93.64    95.00    107.41  73.89
5        7       95.00     92.58    93.12     97.78  68.06
6        8       95.05    102.99    56.25     99.07  50.00
8        8       84.26     93.10    47.50     18.52  50.83
9        7       90.10     97.55    51.25     88.89  63.61
10       7       80.44     90.20    75.00     91.48  39.72
12       8       97.16    103.71    72.50     93.52  63.33
13       7       91.28     83.53    81.25     99.81  92.22

In [45]:
df.fillna(0, inplace=True)
df.head(10)

   Prefix  Assignment  Tutorial  Midterm  TakeHome  Final
0       5       57.14     34.09    64.38     51.48  52.50
1       8       95.05    105.49    67.50     99.07  68.33
2       8       83.70     83.17     0.00     63.15  48.89
3       7        0.00      0.00    49.38    105.93  80.56
4       8       91.32     93.64    95.00    107.41  73.89
5       7       95.00     92.58    93.12     97.78  68.06
6       8       95.05    102.99    56.25     99.07  50.00
7       7       72.85     86.85    60.00      0.00  56.11
8       8       84.26     93.10    47.50     18.52  50.83
9       7       90.10     97.55    51.25     88.89  63.61

In [46]:
df = pd.read_csv('/content/drive/MyDrive/datasets/log.csv')
df.head(20)

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN

In [47]:
df = df.set_index('time')
df = df.sort_index()
df.head(20)

              user          video  playback position paused  volume
time
1469974424  cheryl     intro.html                  5  False    10.0
1469974424     sue  advanced.html                 23  False    10.0
1469974454  cheryl     intro.html                  6    NaN     NaN
1469974454     sue  advanced.html                 24    NaN     NaN
1469974484  cheryl     intro.html                  7    NaN     NaN
1469974514  cheryl     intro.html                  8    NaN     NaN
1469974524     sue  advanced.html                 25    NaN     NaN
1469974544  cheryl     intro.html                  9    NaN     NaN
1469974554     sue  advanced.html                 26    NaN     NaN
1469974574  cheryl     intro.html                 10    NaN     NaN
1469974604  cheryl     intro.html                 11    NaN     NaN
1469974624     sue  advanced.html                 27    NaN     NaN
1469974634  cheryl     intro.html                 12    NaN     NaN
1469974654     sue  advanced.html                 28    NaN     5.0
1469974664  cheryl     intro.html                 13    NaN     NaN
1469974694  cheryl     intro.html                 14    NaN     NaN
1469974724  cheryl     intro.html                 15    NaN     NaN
1469974724     sue  advanced.html                 29    NaN     NaN
1469974754     sue  advanced.html                 30    NaN     NaN
1469974824     sue  advanced.html                 31    NaN     NaN

In [48]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df.head(20)

                           video  playback position paused  volume
time       user
1469974424 cheryl     intro.html                  5  False    10.0
           sue     advanced.html                 23  False    10.0
1469974454 cheryl     intro.html                  6    NaN     NaN
           sue     advanced.html                 24    NaN     NaN
1469974484 cheryl     intro.html                  7    NaN     NaN
1469974514 cheryl     intro.html                  8    NaN     NaN
1469974524 sue     advanced.html                 25    NaN     NaN
1469974544 cheryl     intro.html                  9    NaN     NaN
1469974554 sue     advanced.html                 26    NaN     NaN
1469974574 cheryl     intro.html                 10    NaN     NaN
1469974604 cheryl     intro.html                 11    NaN     NaN
1469974624 sue     advanced.html                 27    NaN     NaN
1469974634 cheryl     intro.html                 12    NaN     NaN
1469974654 sue     advanced.html                 28    NaN     5.0
1469974664 cheryl     intro.html                 13    NaN     NaN
1469974694 cheryl     intro.html                 14    NaN     NaN
1469974724 cheryl     intro.html                 15    NaN     NaN
           sue     advanced.html                 29    NaN     NaN
1469974754 sue     advanced.html                 30    NaN     NaN
1469974824 sue     advanced.html                 31    NaN     NaN

In [49]:
df = df.fillna(method='ffill')
df.head()

<ipython-input-49-c876434e9d91>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')
<ipython-input-49-c876434e9d91>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(method='ffill')

                           video  playback position  paused  volume
time       user
1469974424 cheryl     intro.html                  5   False    10.0
           sue     advanced.html                 23   False    10.0
1469974454 cheryl     intro.html                  6   False    10.0
           sue     advanced.html                 24   False    10.0
1469974484 cheryl     intro.html                  7   False    10.0

In [50]:
df = pd.DataFrame({'A': [1, 1, 2, 3], 'B': [10, 20, 30, 40]})
df

   A   B
0  1  10
1  1  20
2  2  30
3  3  40

In [51]:
df.replace([1,3], [100, 200])

     A   B
0  100  10
1  100  20
2    2  30
3  200  40

In [53]:
df = pd.read_csv('/content/drive/MyDrive/datasets/log.csv')
df.head(20)

          time    user          video  playback position paused  volume
0   1469974424  cheryl     intro.html                  5  False    10.0
1   1469974454  cheryl     intro.html                  6    NaN     NaN
2   1469974544  cheryl     intro.html                  9    NaN     NaN
3   1469974574  cheryl     intro.html                 10    NaN     NaN
4   1469977514     bob     intro.html                  1    NaN     NaN
5   1469977544     bob     intro.html                  1    NaN     NaN
6   1469977574     bob     intro.html                  1    NaN     NaN
7   1469977604     bob     intro.html                  1    NaN     NaN
8   1469974604  cheryl     intro.html                 11    NaN     NaN
9   1469974694  cheryl     intro.html                 14    NaN     NaN
10  1469974724  cheryl     intro.html                 15    NaN     NaN
11  1469974454     sue  advanced.html                 24    NaN     NaN
12  1469974524     sue  advanced.html                 25    NaN     NaN
13  1469974424     sue  advanced.html                 23  False    10.0
14  1469974554     sue  advanced.html                 26    NaN     NaN
15  1469974624     sue  advanced.html                 27    NaN     NaN
16  1469974654     sue  advanced.html                 28    NaN     5.0
17  1469974724     sue  advanced.html                 29    NaN     NaN
18  1469974484  cheryl     intro.html                  7    NaN     NaN
19  1469974514  cheryl     intro.html                  8    NaN     NaN

In [54]:
df.replace(to_replace=".*.html$", value="webpage", regex=True)

          time    user    video  playback position paused  volume
0   1469974424  cheryl  webpage                  5  False    10.0
1   1469974454  cheryl  webpage                  6    NaN     NaN
2   1469974544  cheryl  webpage                  9    NaN     NaN
3   1469974574  cheryl  webpage                 10    NaN     NaN
4   1469977514     bob  webpage                  1    NaN     NaN
5   1469977544     bob  webpage                  1    NaN     NaN
6   1469977574     bob  webpage                  1    NaN     NaN
7   1469977604     bob  webpage                  1    NaN     NaN
8   1469974604  cheryl  webpage                 11    NaN     NaN
9   1469974694  cheryl  webpage                 14    NaN     NaN
10  1469974724  cheryl  webpage                 15    NaN     NaN
11  1469974454     sue  webpage                 24    NaN     NaN
12  1469974524     sue  webpage                 25    NaN     NaN
13  1469974424     sue  webpage                 23  False    10.0
14  1469974554     sue  webpage                 26    NaN     NaN
15  1469974624     sue  webpage                 27    NaN     NaN
16  1469974654     sue  webpage                 28    NaN     5.0
17  1469974724     sue  webpage                 29    NaN     NaN
18  1469974484  cheryl  webpage                  7    NaN     NaN
19  1469974514  cheryl  webpage                  8    NaN     NaN
20  1469974754     sue  webpage                 30    NaN     NaN
21  1469974824     sue  webpage                 31    NaN     NaN
22  1469974854     sue  webpage                 32    NaN     NaN
23  1469974924     sue  webpage                 33    NaN     NaN
24  1469977424     bob  webpage                  1   True    10.0
25  1469977454     bob  webpage                  1    NaN     NaN
26  1469977484     bob  webpage                  1    NaN     NaN
27  1469977634     bob  webpage                  1    NaN     NaN
28  1469977664     bob  webpage                  1    NaN     NaN
29  1469974634  cheryl  webpage                 12    NaN     NaN
30  1469974664  cheryl  webpage                 13    NaN     NaN
31  1469977694     bob  webpage                  1    NaN     NaN
32  1469977724     bob  webpage                  1    NaN     NaN

In [55]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/datasets/presidents.csv')
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

In [56]:
df["First"] = df['President']
df["First"] = df["First"].replace("[ ].*", "", regex=True)
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James

In [57]:
del (df['First'])

In [58]:
def splitname(row):
    row['First'] = row['President'].split(" ")[0]
    row['Last'] = row['President'].split(" ")[-1]
    return row

df = df.apply(splitname, axis='columns')
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First,Last
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

In [59]:
del(df['First'])
del(df['Last'])

In [72]:
pattern="(^[\w]*)(?:.* )([\w]*$)"

df['President'].str.extract(pattern)

             0           1
0       George  Washington
1         John       Adams
2       Thomas   Jefferson
3        James     Madison
4        James      Monroe
5         John       Adams
6       Andrew     Jackson
7       Martin       Buren
8      William    Harrison
9         John       Tyler
10       James        Polk
11     Zachary      Taylor
12     Millard    Fillmore
13    Franklin      Pierce
14       James    Buchanan
15     Abraham     Lincoln
16      Andrew     Johnson
17     Ulysses       Grant
18  Rutherford       Hayes
19       James    Garfield
20     Chester      Arthur
21      Grover   Cleveland
22    Benjamin    Harrison
23      Grover   Cleveland
24     William    McKinley
25    Theodore   Roosevelt
26     William        Taft
27     Woodrow      Wilson
28      Warren     Harding
29      Calvin    Coolidge
30     Herbert      Hoover
31    Franklin   Roosevelt
32       Harry      Truman
33      Dwight  Eisenhower
34        John     Kennedy
35      Lyndon     Johnson
36     Richard       Nixon
37      Gerald        Ford
38       Jimmy      Carter
39      Ronald      Reagan
40      George        Bush
41        Bill     Clinton
42      George        Bush
43      Barack       Obama

In [74]:
pattern == "(?P<First>^[\w]*)(?:.* )(?P<Last>[\w]*$)"

names = df['President'].str.extract(pattern)
names

             0           1
0       George  Washington
1         John       Adams
2       Thomas   Jefferson
3        James     Madison
4        James      Monroe
5         John       Adams
6       Andrew     Jackson
7       Martin       Buren
8      William    Harrison
9         John       Tyler
10       James        Polk
11     Zachary      Taylor
12     Millard    Fillmore
13    Franklin      Pierce
14       James    Buchanan
15     Abraham     Lincoln
16      Andrew     Johnson
17     Ulysses       Grant
18  Rutherford       Hayes
19       James    Garfield
20     Chester      Arthur
21      Grover   Cleveland
22    Benjamin    Harrison
23      Grover   Cleveland
24     William    McKinley
25    Theodore   Roosevelt
26     William        Taft
27     Woodrow      Wilson
28      Warren     Harding
29      Calvin    Coolidge
30     Herbert      Hoover
31    Franklin   Roosevelt
32       Harry      Truman
33      Dwight  Eisenhower
34        John     Kennedy
35      Lyndon     Johnson
36     Richard       Nixon
37      Gerald        Ford
38       Jimmy      Carter
39      Ronald      Reagan
40      George        Bush
41        Bill     Clinton
42      George        Bush
43      Barack       Obama

In [75]:
df["First"] = names["First"]
df["Last"] = names["Last"]
df.head()

KeyError: 'First'

In [76]:
pattern = "(?P<First>^[\w]*)(?:.* )(?P<Last>[\w]*$)"

# Extract names using the pattern
names = df['President'].str.extract(pattern)

# Reset the index of names to match df's index
names = names.set_index(df.index)

# Assign the extracted columns to df
df["First"] = names["First"]
df["Last"] = names["Last"]
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First,Last
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

In [78]:
df["Born"] = df["Born"].str.extract("([\w]{3} [\w]{1,2}, [\w]{4})")
df["Born"].head()

0    Feb 22, 1732
1    Oct 30, 1735
2    Apr 13, 1743
3    Mar 16, 1751
4    Apr 28, 1758
Name: Born, dtype: object

In [79]:
df["Born"] = pd.to_datetime(df["Born"])
df["Born"].head()

0   1732-02-22
1   1735-10-30
2   1743-04-13
3   1751-03-16
4   1758-04-28
Name: Born, dtype: datetime64[ns]

In [80]:
import pandas as pd
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj1 = pd.Series(sdata)
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj2 = pd.Series(sdata, index=states)
obj3 = pd.isnull(obj2)

In [82]:
obj3['California']

True

In [83]:
obj2['California'] == None

False

In [84]:
import math
math.isnan(obj2['California'])

True

In [85]:
x = obj2['California']
obj2['California'] != x

True

In [90]:
import pandas as pd
d = {'1': 'Alice','2': 'Bob','3': 'Rita','4': 'Molly','5': 'Ryan'}
S = pd.Series(d)
S

1    Alice
2      Bob
3     Rita
4    Molly
5     Ryan
dtype: object

In [93]:
S.iloc[0:3]

1    Alice
2      Bob
3     Rita
dtype: object

In [91]:
S.iloc[0:3]

1    Alice
2      Bob
3     Rita
dtype: object

In [94]:
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age,First,Last
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

In [96]:
df.rename(mapper = lambda x: x.upper(), axis=1, inplace = True)
df.head()

,#,PRESIDENT,BORN,AGE ATSTART OF PRESIDENCY,AGE ATEND OF PRESIDENCY,POST-PRESIDENCYTIMESPAN,DIED,AGE,FIRST,LAST
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

In [98]:
df.head()
df.rename(mapper = lambda x: x.lower(), axis=1, inplace = True)
df.head()

,#,president,born,age atstart of presidency,age atend of presidency,post-presidencytimespan,died,age,first,last
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe

In [99]:
df.rename(mapper = lambda x: x.upper(), axis = 1)

,#,PRESIDENT,BORN,AGE ATSTART OF PRESIDENCY,AGE ATEND OF PRESIDENCY,POST-PRESIDENCYTIMESPAN,DIED,AGE,FIRST,LAST
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days","Feb 23, 1848","80 years, 227 days",John,Adams
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days","Jun 8, 1845","78 years, 85 days",Andrew,Jackson
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days","Jul 24, 1862","79 years, 231 days",Martin,Buren
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,"Apr 4, 1841","68 years, 54 days",William,Harrison
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days","Jan 18, 1862","71 years, 295 days",John,Tyler
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,"Jun 15, 1849","53 years, 225 days",James,Polk
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,"Jul 9, 1850","65 years, 227 days",Zachary,Taylor
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days","Mar 8, 1874","74 years, 60 days",Millard,Fillmore
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days","Oct 8, 1869","64 years, 319 days",Franklin,Pierce
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days","Jun 1, 1868","77 years, 39 days",James,Buchanan
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,"Apr 15, 1865","56 years, 62 days",Abraham,Lincoln
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days","Jul 31, 1875","66 years, 214 days",Andrew,Johnson
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days","Jul 23, 1885","63 years, 87 days",Ulysses,Grant
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days","Jan 17, 1893","70 years, 105 days",Rutherford,Hayes
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,"Sep 19, 1881","49 years, 304 days",James,Garfield
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days","Nov 18, 1886","57 years, 44 days",Chester,Arthur
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]","Jun 24, 1908","71 years, 98 days",Grover,Cleveland
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days","Mar 13, 1901","67 years, 205 days",Benjamin,Harrison
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]","Jun 24, 1908","71 years, 98 days",Grover,Cleveland
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,"Sep 14, 1901","58 years, 228 days",William,McKinley
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days","Jan 6, 1919","60 years, 71 days",Theodore,Roosevelt
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days","Mar 8, 1930","72 years, 174 days",William,Taft
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days","Feb 3, 1924","67 years, 37 days",Woodrow,Wilson
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,"Aug 2, 1923","57 years, 273 days",Warren,Harding
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days","Jan 5, 1933","60 years, 185 days",Calvin,Coolidge
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days","Oct 20, 1964","90 years, 71 days",Herbert,Hoover
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,"Apr 12, 1945","63 years, 72 days",Franklin,Roosevelt
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days","Dec 26, 1972","88 years, 232 days",Harry,Truman
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days","Mar 28, 1969","78 years, 165 days",Dwight,Eisenhower
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,"Nov 22, 1963","46 years, 177 days",John,Kennedy
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days","Jan 22, 1973","64 years, 148 days",Lyndon,Johnson
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days","Apr 22, 1994","81 years, 103 days",Richard,Nixon
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days","Dec 26, 2006","93 years, 165 days",Gerald,Ford
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",(living),"94 years, 286 days",Jimmy,Carter
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days","Jun 5, 2004","93 years, 120 days",Ronald,Reagan
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days","Nov 30, 2018","94 years, 171 days",George,Bush
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",(living),"72 years, 329 days",Bill,Clinton
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",(living),"73 years, 8 days",George,Bush
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",(living),"57 years, 344 days",Barack,Obama

In [100]:
df.rename(mapper = lambda x: x.lower(), axis = 1)

,#,president,born,age atstart of presidency,age atend of presidency,post-presidencytimespan,died,age,first,last
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington
1,2,John Adams,1735-10-30,"61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days",John,Adams
2,3,Thomas Jefferson,1743-04-13,"57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days",Thomas,Jefferson
3,4,James Madison,1751-03-16,"57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days",James,Madison
4,5,James Monroe,1758-04-28,"58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days",James,Monroe
5,6,John Quincy Adams,1767-07-11,"57 years, 236 daysMar 4, 1825","61 years, 236 daysMar 4, 1829","18 years, 356 days","Feb 23, 1848","80 years, 227 days",John,Adams
6,7,Andrew Jackson,1767-03-15,"61 years, 354 daysMar 4, 1829","69 years, 354 daysMar 4, 1837","8 years, 96 days","Jun 8, 1845","78 years, 85 days",Andrew,Jackson
7,8,Martin Van Buren,1782-12-05,"54 years, 89 daysMar 4, 1837","58 years, 89 daysMar 4, 1841","21 years, 142 days","Jul 24, 1862","79 years, 231 days",Martin,Buren
8,9,William H. Harrison,1773-02-09,"68 years, 23 daysMar 4, 1841","68 years, 54 days Apr 4, 1841[b]",NaN,"Apr 4, 1841","68 years, 54 days",William,Harrison
9,10,John Tyler,1790-03-29,"51 years, 6 daysApr 4, 1841","54 years, 340 daysMar 4, 1845","16 years, 320 days","Jan 18, 1862","71 years, 295 days",John,Tyler
10,11,James K. Polk,1795-11-02,"49 years, 122 daysMar 4, 1845","53 years, 122 daysMar 4, 1849",103 days,"Jun 15, 1849","53 years, 225 days",James,Polk
11,12,Zachary Taylor,1784-11-24,"64 years, 100 daysMar 4, 1849","65 years, 227 daysJul 9, 1850[b]",NaN,"Jul 9, 1850","65 years, 227 days",Zachary,Taylor
12,13,Millard Fillmore,1800-01-07,"50 years, 183 daysJul 9, 1850","53 years, 56 daysMar 4, 1853","21 years, 4 days","Mar 8, 1874","74 years, 60 days",Millard,Fillmore
13,14,Franklin Pierce,1804-11-23,"48 years, 101 daysMar 4, 1853","52 years, 101 daysMar 4, 1857","12 years, 218 days","Oct 8, 1869","64 years, 319 days",Franklin,Pierce
14,15,James Buchanan,1791-04-23,"65 years, 315 daysMar 4, 1857","69 years, 315 daysMar 4, 1861","7 years, 89 days","Jun 1, 1868","77 years, 39 days",James,Buchanan
15,16,Abraham Lincoln,1809-02-12,"52 years, 20 daysMar 4, 1861","56 years, 62 daysApr 15, 1865[b]",NaN,"Apr 15, 1865","56 years, 62 days",Abraham,Lincoln
16,17,Andrew Johnson,1808-12-29,"56 years, 107 daysApr 15, 1865","60 years, 65 daysMar 4, 1869","6 years, 149 days","Jul 31, 1875","66 years, 214 days",Andrew,Johnson
17,18,Ulysses S. Grant,1822-04-27,"46 years, 311 daysMar 4, 1869","54 years, 311 daysMar 4, 1877","8 years, 141 days","Jul 23, 1885","63 years, 87 days",Ulysses,Grant
18,19,Rutherford B. Hayes,1822-10-04,"54 years, 151 daysMar 4, 1877","58 years, 151 daysMar 4, 1881","11 years, 319 days","Jan 17, 1893","70 years, 105 days",Rutherford,Hayes
19,20,James A. Garfield,1831-11-19,"49 years, 105 daysMar 4, 1881","49 years, 304 daysSep 19, 1881[b]",NaN,"Sep 19, 1881","49 years, 304 days",James,Garfield
20,21,Chester A. Arthur,1829-10-05,"51 years, 349 daysSep 19, 1881","55 years, 150 daysMar 4, 1885","1 year, 259 days","Nov 18, 1886","57 years, 44 days",Chester,Arthur
21,22,Grover Cleveland,1837-03-18,"47 years, 351 daysMar 4, 1885","51 years, 351 daysMar 4, 1889","4 years, 0 days[c]","Jun 24, 1908","71 years, 98 days",Grover,Cleveland
22,23,Benjamin Harrison,1833-08-20,"55 years, 196 daysMar 4, 1889","59 years, 196 daysMar 4, 1893","8 years, 9 days","Mar 13, 1901","67 years, 205 days",Benjamin,Harrison
23,24,Grover Cleveland,1837-03-18,"55 years, 351 daysMar 4, 1893","59 years, 351 daysMar 4, 1897","11 years, 112 days[d]","Jun 24, 1908","71 years, 98 days",Grover,Cleveland
24,25,William McKinley,1843-01-29,"54 years, 34 daysMar 4, 1897","58 years, 228 daysSep 14, 1901[b]",NaN,"Sep 14, 1901","58 years, 228 days",William,McKinley
25,26,Theodore Roosevelt,1858-10-27,"42 years, 322 daysSep 14, 1901","50 years, 128 daysMar 4, 1909","9 years, 308 days","Jan 6, 1919","60 years, 71 days",Theodore,Roosevelt
26,27,William H. Taft,1857-09-15,"51 years, 170 daysMar 4, 1909","55 years, 170 daysMar 4, 1913","17 years, 4 days","Mar 8, 1930","72 years, 174 days",William,Taft
27,28,Woodrow Wilson,1856-12-28,"56 years, 66 daysMar 4, 1913","64 years, 66 daysMar 4, 1921","2 years, 336 days","Feb 3, 1924","67 years, 37 days",Woodrow,Wilson
28,29,Warren G. Harding,1865-11-02,"55 years, 122 daysMar 4, 1921","57 years, 273 daysAug 2, 1923[b]",NaN,"Aug 2, 1923","57 years, 273 days",Warren,Harding
29,30,Calvin Coolidge,1872-07-04,"51 years, 29 daysAug 2, 1923","56 years, 243 daysMar 4, 1929","3 years, 307 days","Jan 5, 1933","60 years, 185 days",Calvin,Coolidge
30,31,Herbert Hoover,1874-08-10,"54 years, 206 daysMar 4, 1929","58 years, 206 daysMar 4, 1933","31 years, 230 days","Oct 20, 1964","90 years, 71 days",Herbert,Hoover
31,32,Franklin D. Roosevelt,1882-01-30,"51 years, 33 daysMar 4, 1933","63 years, 72 daysApr 12, 1945[b]",NaN,"Apr 12, 1945","63 years, 72 days",Franklin,Roosevelt
32,33,Harry S. Truman,1884-05-08,"60 years, 339 daysApr 12, 1945","68 years, 257 daysJan 20, 1953","19 years, 341 days","Dec 26, 1972","88 years, 232 days",Harry,Truman
33,34,Dwight D. Eisenhower,1890-10-14,"62 years, 98 daysJan 20, 1953","70 years, 98 daysJan 20, 1961","8 years, 67 days","Mar 28, 1969","78 years, 165 days",Dwight,Eisenhower
34,35,John F. Kennedy,1917-05-29,"43 years, 236 daysJan 20, 1961","46 years, 177 daysNov 22, 1963[b]",NaN,"Nov 22, 1963","46 years, 177 days",John,Kennedy
35,36,Lyndon B. Johnson,1908-08-27,"55 years, 87 daysNov 22, 1963","60 years, 146 daysJan 20, 1969","4 years, 2 days","Jan 22, 1973","64 years, 148 days",Lyndon,Johnson
36,37,Richard Nixon,1913-01-09,"56 years, 11 daysJan 20, 1969","61 years, 212 daysAug 9, 1974[e]","19 years, 256 days","Apr 22, 1994","81 years, 103 days",Richard,Nixon
37,38,Gerald Ford,1913-07-14,"61 years, 26 daysAug 9, 1974","63 years, 190 daysJan 20, 1977","29 years, 340 days","Dec 26, 2006","93 years, 165 days",Gerald,Ford
38,39,Jimmy Carter,1924-10-01,"52 years, 111 daysJan 20, 1977","56 years, 111 daysJan 20, 1981","38 years, 175 days",(living),"94 years, 286 days",Jimmy,Carter
39,40,Ronald Reagan,1911-02-06,"69 years, 349 daysJan 20, 1981","77 years, 349 daysJan 20, 1989","15 years, 137 days","Jun 5, 2004","93 years, 120 days",Ronald,Reagan
40,41,George H. W. Bush,1924-06-12,"64 years, 222 daysJan 20, 1989","68 years, 222 daysJan 20, 1993","25 years, 314 days","Nov 30, 2018","94 years, 171 days",George,Bush
41,42,Bill Clinton,1946-08-19,"46 years, 154 daysJan 20, 1993","54 years, 154 daysJan 20, 2001","18 years, 175 days",(living),"72 years, 329 days",Bill,Clinton
42,43,George W. Bush,1946-07-06,"54 years, 198 daysJan 20, 2001","62 years, 198 daysJan 20, 2009","10 years, 175 days",(living),"73 years, 8 days",George,Bush
43,44,Barack Obama,1961-08-04,"47 years, 169 daysJan 20, 2009","55 years, 169 daysJan 20, 2017","2 years, 175 days",(living),"57 years, 344 days",Barack,Obama

In [105]:
df = df.rename(mapper = lambda x:x.upper(), axis = 'columns')
df.head(1)

,#,PRESIDENT,BORN,AGE ATSTART OF PRESIDENCY,AGE ATEND OF PRESIDENCY,POST-PRESIDENCYTIMESPAN,DIED,AGE,FIRST,LAST
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington

In [108]:
df = df.rename(mapper = lambda x: x.lower(), axis = 'columns')
df.head(1)

,#,president,born,age atstart of presidency,age atend of presidency,post-presidencytimespan,died,age,first,last
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington

In [109]:
df = df.rename(mapper=lambda x: x.upper(), axis=1)
df.head(1)

,#,PRESIDENT,BORN,AGE ATSTART OF PRESIDENCY,AGE ATEND OF PRESIDENCY,POST-PRESIDENCYTIMESPAN,DIED,AGE,FIRST,LAST
0,1,George Washington,1732-02-22,"57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days",George,Washington

In [116]:
import pandas as pd
df = pd.Series({
           'Serial No': [1, 2, 3, 4, 5],
           'gre score':[337, 324, 316, 322, 314],
           'toefl score':[118, 107, 104, 110, 103]})

In [121]:
df = pd.DataFrame(df)
print(df)

                                     0
Serial No              [1, 2, 3, 4, 5]
gre score    [337, 324, 316, 322, 314]
toefl score  [118, 107, 104, 110, 103]

In [123]:
data = [[1,337,118], [2, 324, 107], [3, 316, 104], [4,322, 110],
        [5, 314, 103]]

df = pd.DataFrame(data, columns = ['Serial No', 'gre score', 'toefl score'])
print(df)

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
2          3        316          104
3          4        322          110
4          5        314          103

In [124]:
df

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
2          3        316          104
3          4        322          110
4          5        314          103

In [125]:
df.where(df['toefl score']>105)

   Serial No  gre score  toefl score
0        1.0      337.0        118.0
1        2.0      324.0        107.0
2        NaN        NaN          NaN
3        4.0      322.0        110.0
4        NaN        NaN          NaN

In [126]:
df

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
2          3        316          104
3          4        322          110
4          5        314          103

In [128]:
df[df['toefl score'] > 105]

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
3          4        322          110

In [129]:
df

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
2          3        316          104
3          4        322          110
4          5        314          103

In [130]:
df.where(df['toefl score']>105).dropna()

   Serial No  gre score  toefl score
0        1.0      337.0        118.0
1        2.0      324.0        107.0
3        4.0      322.0        110.0

In [131]:
df

   Serial No  gre score  toefl score
0          1        337          118
1          2        324          107
2          3        316          104
3          4        322          110
4          5        314          103

In [134]:
df=pd.read_csv('/content/drive/MyDrive/datasets/presidents.csv')
df.head()

,#,President,Born,Age atstart of presidency,Age atend of presidency,Post-presidencytimespan,Died,Age
0,1,George Washington,"Feb 22, 1732[a]","57 years, 67 daysApr 30, 1789","65 years, 10 daysMar 4, 1797","2 years, 285 days","Dec 14, 1799","67 years, 295 days"
1,2,John Adams,"Oct 30, 1735[a]","61 years, 125 daysMar 4, 1797","65 years, 125 daysMar 4, 1801","25 years, 122 days","Jul 4, 1826","90 years, 247 days"
2,3,Thomas Jefferson,"Apr 13, 1743[a]","57 years, 325 daysMar 4, 1801","65 years, 325 daysMar 4, 1809","17 years, 122 days","Jul 4, 1826","83 years, 82 days"
3,4,James Madison,"Mar 16, 1751[a]","57 years, 353 daysMar 4, 1809","65 years, 353 daysMar 4, 1817","19 years, 116 days","Jun 28, 1836","85 years, 104 days"
4,5,James Monroe,"Apr 28, 1758","58 years, 310 daysMar 4, 1817","66 years, 310 daysMar 4, 1825","6 years, 122 days","Jul 4, 1831","73 years, 67 days"

In [137]:
df.iloc['George Washington']

TypeError: Cannot index by location index with a non-integer key